// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkT0fXHMJWOtCi6OV-JB7tN1PBqXU893g',
    appId: '1:958321128204:android:e52926ad2c2b3d350acf29',
    messagingSenderId: '958321128204',
    projectId: 'chatapp-d2e0f',
    databaseURL: 'https://chatapp-d2e0f.firebaseio.com',
    storageBucket: 'chatapp-d2e0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7aPH8tlecRQIn4_iGMn5oF6iedZ55SBE',
    appId: '1:958321128204:ios:587fc117b2f0379b0acf29',
    messagingSenderId: '958321128204',
    projectId: 'chatapp-d2e0f',
    databaseURL: 'https://chatapp-d2e0f.firebaseio.com',
    storageBucket: 'chatapp-d2e0f.appspot.com',
    iosClientId: '958321128204-ihictcac24v7kjsnhc48r9c7aiancb7h.apps.googleusercontent.com',
    iosBundleId: 'com.karenruimy.goddessmembership',
  );
}
